services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docker_app_development

  app:
    build: .
    command: bash entrypoint.sh
    volumes:
      - .:/app
      - /app/tmp:/app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/docker_app_development"

volumes:
  db_data:
