TEST_POSTGRES_USERNAME: "postgres"
TEST_POSTGRES_PASSWORD: "postgres"
TEST_DATABASE_NAME: "docker_app_test"

DEVELOPMENT_POSTGRES_USERNAME: "postgres"
DEVELOPMENT_POSTGRES_PASSWORD: "postgres"
DEVELOPMENT_DATABASE_NAME: "docker_app_development"
