services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    user: root  # 👈 this gives Jenkins root privileges inside the container
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Access host Docker

volumes:
  jenkins_home:
